# Generated by Django 3.0.2 on 2020-01-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracao',
            new_name='Recurso',
        ),
    ]
