# Generated by Django 3.0.2 on 2020-01-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20200102_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
